import { ISpecialCharacterGroup } from '../interface'

export const DEFAULT_CHARACTERS: ISpecialCharacterGroup[] = [
  {
    name: '常用符号',
    characters: [
      { char: '©', name: '版权' },
      { char: '®', name: '注册商标' },
      { char: '™', name: '商标' },
      { char: '§', name: '章节' },
      { char: '¶', name: '段落' },
      { char: '†', name: '剑标' },
      { char: '‡', name: '双剑标' },
      { char: '•', name: '项目符号' },
      { char: '…', name: '省略号' },
      { char: '—', name: '破折号' },
      { char: '–', name: '短破折号' },
      { char: '°', name: '度' },
      { char: '‰', name: '千分号' },
      { char: '‱', name: '万分号' },
      { char: '№', name: '序号' },
      { char: '℗', name: '录音版权' },
      { char: '℠', name: '服务标记' },
      { char: '℡', name: '电话' },
      { char: '℀', name: '账户' },
      { char: '℁', name: '地址' },
      { char: '℅', name: '照顾' },
      { char: '※', name: '米印' },
      { char: '¡', name: '倒感叹号' },
      { char: '¿', name: '倒问号' }
    ]
  },
  {
    name: '数学符号',
    characters: [
      { char: '±', name: '正负' },
      { char: '×', name: '乘' },
      { char: '÷', name: '除' },
      { char: '≠', name: '不等于' },
      { char: '≡', name: '恒等于' },
      { char: '≌', name: '全等于' },
      { char: '≈', name: '约等于' },
      { char: '≃', name: '渐近等于' },
      { char: '≅', name: '同构' },
      { char: '≤', name: '小于等于' },
      { char: '≥', name: '大于等于' },
      { char: '≮', name: '不小于' },
      { char: '≯', name: '不大于' },
      { char: '∞', name: '无穷' },
      { char: '∑', name: '求和' },
      { char: '∏', name: '求积' },
      { char: '√', name: '平方根' },
      { char: '∛', name: '立方根' },
      { char: '∜', name: '四次方根' },
      { char: '∫', name: '积分' },
      { char: '∬', name: '二重积分' },
      { char: '∮', name: '曲线积分' },
      { char: '∂', name: '偏导' },
      { char: '∆', name: '增量' },
      { char: '∇', name: '梯度' },
      { char: 'π', name: '圆周率' },
      { char: '∝', name: '成正比' },
      { char: '∠', name: '角' },
      { char: '∟', name: '直角' },
      { char: '⌒', name: '弧' },
      { char: '∣', name: '整除' },
      { char: '∤', name: '不整除' },
      { char: '∥', name: '平行' },
      { char: '∦', name: '不平行' },
      { char: '⊥', name: '垂直' },
      { char: '∧', name: '逻辑与' },
      { char: '∨', name: '逻辑或' },
      { char: '∩', name: '交集' },
      { char: '∪', name: '并集' },
      { char: '∅', name: '空集' },
      { char: '∈', name: '属于' },
      { char: '∉', name: '不属于' },
      { char: '⊆', name: '包含于' },
      { char: '⊇', name: '包含' },
      { char: '⊂', name: '真包含于' },
      { char: '⊃', name: '真包含' },
      { char: '∵', name: '因为' },
      { char: '∴', name: '所以' },
      { char: '∃', name: '存在' },
      { char: '∀', name: '任意' },
      { char: '¬', name: '非' },
      { char: '⊕', name: '异或' },
      { char: '⊙', name: '同或' }
    ]
  },
  {
    name: '希腊字母',
    characters: [
      { char: 'α', name: 'Alpha' },
      { char: 'β', name: 'Beta' },
      { char: 'γ', name: 'Gamma' },
      { char: 'δ', name: 'Delta' },
      { char: 'ε', name: 'Epsilon' },
      { char: 'ζ', name: 'Zeta' },
      { char: 'η', name: 'Eta' },
      { char: 'θ', name: 'Theta' },
      { char: 'ι', name: 'Iota' },
      { char: 'κ', name: 'Kappa' },
      { char: 'λ', name: 'Lambda' },
      { char: 'μ', name: 'Mu' },
      { char: 'ν', name: 'Nu' },
      { char: 'ξ', name: 'Xi' },
      { char: 'ο', name: 'Omicron' },
      { char: 'π', name: 'Pi' },
      { char: 'ρ', name: 'Rho' },
      { char: 'σ', name: 'Sigma' },
      { char: 'τ', name: 'Tau' },
      { char: 'υ', name: 'Upsilon' },
      { char: 'φ', name: 'Phi' },
      { char: 'χ', name: 'Chi' },
      { char: 'ψ', name: 'Psi' },
      { char: 'ω', name: 'Omega' },
      { char: 'Α', name: 'Alpha大写' },
      { char: 'Β', name: 'Beta大写' },
      { char: 'Γ', name: 'Gamma大写' },
      { char: 'Δ', name: 'Delta大写' },
      { char: 'Ε', name: 'Epsilon大写' },
      { char: 'Ζ', name: 'Zeta大写' },
      { char: 'Η', name: 'Eta大写' },
      { char: 'Θ', name: 'Theta大写' },
      { char: 'Ι', name: 'Iota大写' },
      { char: 'Κ', name: 'Kappa大写' },
      { char: 'Λ', name: 'Lambda大写' },
      { char: 'Μ', name: 'Mu大写' },
      { char: 'Ν', name: 'Nu大写' },
      { char: 'Ξ', name: 'Xi大写' },
      { char: 'Ο', name: 'Omicron大写' },
      { char: 'Π', name: 'Pi大写' },
      { char: 'Ρ', name: 'Rho大写' },
      { char: 'Σ', name: 'Sigma大写' },
      { char: 'Τ', name: 'Tau大写' },
      { char: 'Υ', name: 'Upsilon大写' },
      { char: 'Φ', name: 'Phi大写' },
      { char: 'Χ', name: 'Chi大写' },
      { char: 'Ψ', name: 'Psi大写' },
      { char: 'Ω', name: 'Omega大写' }
    ]
  },
  {
    name: '单位符号',
    characters: [
      // 货币
      { char: '€', name: '欧元' },
      { char: '£', name: '英镑' },
      { char: '¥', name: '日元/人民币' },
      { char: '¢', name: '美分' },
      { char: '＄', name: '美元' },
      { char: '₩', name: '韩元' },
      { char: '₽', name: '卢布' },
      { char: '₹', name: '卢比' },
      // 长度/面积/体积
      { char: '㎜', name: '毫米' },
      { char: '㎝', name: '厘米' },
      { char: 'dm', name: '分米' },
      { char: 'm', name: '米' },
      { char: '㎞', name: '千米' },
      { char: '㎡', name: '平方米' },
      { char: '㎥', name: '立方米' },
      { char: 'μm', name: '微米' },
      { char: 'nm', name: '纳米' },
      { char: 'Å', name: '埃' },
      // 重量
      { char: '㎎', name: '毫克' },
      { char: 'g', name: '克' },
      { char: '㎏', name: '千克' },
      { char: 't', name: '吨' },
      // 容积
      { char: 'mL', name: '毫升' },
      { char: 'L', name: '升' },
      // 温度
      { char: '℃', name: '摄氏度' },
      { char: '℉', name: '华氏度' },
      { char: 'K', name: '开尔文' },
      // 电学/物理
      { char: 'Ω', name: '欧姆' },
      { char: 'μΩ', name: '微欧' },
      { char: 'mΩ', name: '毫欧' },
      { char: 'kΩ', name: '千欧' },
      { char: 'MΩ', name: '兆欧' },
      { char: 'V', name: '伏特' },
      { char: 'A', name: '安培' },
      { char: 'W', name: '瓦特' },
      { char: 'Hz', name: '赫兹' },
      { char: '㎐', name: '赫兹' }
    ]
  },
  {
    name: '数字序号',
    characters: [
      { char: 'Ⅰ', name: '罗马数字1' },
      { char: 'Ⅱ', name: '罗马数字2' },
      { char: 'Ⅲ', name: '罗马数字3' },
      { char: 'Ⅳ', name: '罗马数字4' },
      { char: 'Ⅴ', name: '罗马数字5' },
      { char: 'Ⅵ', name: '罗马数字6' },
      { char: 'Ⅶ', name: '罗马数字7' },
      { char: 'Ⅷ', name: '罗马数字8' },
      { char: 'Ⅸ', name: '罗马数字9' },
      { char: 'Ⅹ', name: '罗马数字10' },
      { char: 'Ⅺ', name: '罗马数字11' },
      { char: 'Ⅻ', name: '罗马数字12' },
      { char: 'ⅰ', name: '小写罗马1' },
      { char: 'ⅱ', name: '小写罗马2' },
      { char: 'ⅲ', name: '小写罗马3' },
      { char: 'ⅳ', name: '小写罗马4' },
      { char: 'ⅴ', name: '小写罗马5' },
      { char: 'ⅵ', name: '小写罗马6' },
      { char: 'ⅶ', name: '小写罗马7' },
      { char: 'ⅷ', name: '小写罗马8' },
      { char: 'ⅸ', name: '小写罗马9' },
      { char: 'ⅹ', name: '小写罗马10' },
      { char: '①', name: '圆圈1' },
      { char: '②', name: '圆圈2' },
      { char: '③', name: '圆圈3' },
      { char: '④', name: '圆圈4' },
      { char: '⑤', name: '圆圈5' },
      { char: '⑥', name: '圆圈6' },
      { char: '⑦', name: '圆圈7' },
      { char: '⑧', name: '圆圈8' },
      { char: '⑨', name: '圆圈9' },
      { char: '⑩', name: '圆圈10' },
      { char: '❶', name: '黑圆圈1' },
      { char: '❷', name: '黑圆圈2' },
      { char: '❸', name: '黑圆圈3' },
      { char: '❹', name: '黑圆圈4' },
      { char: '❺', name: '黑圆圈5' },
      { char: '❻', name: '黑圆圈6' },
      { char: '❼', name: '黑圆圈7' },
      { char: '❽', name: '黑圆圈8' },
      { char: '❾', name: '黑圆圈9' },
      { char: '❿', name: '黑圆圈10' },
      { char: '⑴', name: '括号1' },
      { char: '⑵', name: '括号2' },
      { char: '⑶', name: '括号3' },
      { char: '⑷', name: '括号4' },
      { char: '⑸', name: '括号5' },
      { char: '⑹', name: '括号6' },
      { char: '⑺', name: '括号7' },
      { char: '⑻', name: '括号8' },
      { char: '⑼', name: '括号9' },
      { char: '⑽', name: '括号10' },
      { char: '⒈', name: '点1' },
      { char: '⒉', name: '点2' },
      { char: '⒊', name: '点3' },
      { char: '⒋', name: '点4' },
      { char: '⒌', name: '点5' },
      { char: '⒍', name: '点6' },
      { char: '⒎', name: '点7' },
      { char: '⒏', name: '点8' },
      { char: '⒐', name: '点9' },
      { char: '⒑', name: '点10' },
      { char: '½', name: '二分之一' },
      { char: '⅓', name: '三分之一' },
      { char: '⅔', name: '三分之二' },
      { char: '¼', name: '四分之一' },
      { char: '¾', name: '四分之三' },
      { char: '⅛', name: '八分之一' },
      { char: '⅜', name: '八分之三' },
      { char: '⅝', name: '八分之五' },
      { char: '⅞', name: '八分之七' }
    ]
  },
  {
    name: '箭头符号',
    characters: [
      { char: '←', name: '左箭头' },
      { char: '↑', name: '上箭头' },
      { char: '→', name: '右箭头' },
      { char: '↓', name: '下箭头' },
      { char: '↔', name: '左右箭头' },
      { char: '↕', name: '上下箭头' },
      { char: '⇐', name: '左双箭头' },
      { char: '⇑', name: '上双箭头' },
      { char: '⇒', name: '右双箭头' },
      { char: '⇓', name: '下双箭头' },
      { char: '⇔', name: '左右双箭头' },
      { char: '⇕', name: '上下双箭头' },
      { char: '↖', name: '左上' },
      { char: '↗', name: '右上' },
      { char: '↘', name: '右下' },
      { char: '↙', name: '左下' },
      { char: '↺', name: '逆时针' },
      { char: '↻', name: '顺时针' },
      { char: '↩', name: '返回' },
      { char: '↪', name: '进入' },
      { char: '➔', name: '粗右箭头' },
      { char: '➜', name: '粗右箭头' },
      { char: '➝', name: '三角箭头' },
      { char: '➞', name: '实心箭头' },
      { char: '➟', name: '虚线箭头' },
      { char: '➠', name: '三角虚线' },
      { char: '➡', name: '黑右箭头' },
      { char: '➢', name: '黑三角头' },
      { char: '➤', name: '黑三角头' },
      { char: '➥', name: '黑右下' },
      { char: '➦', name: '黑右上' },
      { char: '➧', name: '黑右' }
    ]
  },
  {
    name: '图形符号',
    characters: [
      { char: '★', name: '实心五角星' },
      { char: '☆', name: '空心五角星' },
      { char: '✦', name: '四角星' },
      { char: '✧', name: '空心四角星' },
      { char: '◆', name: '实心菱形' },
      { char: '◇', name: '空心菱形' },
      { char: '●', name: '实心圆' },
      { char: '○', name: '空心圆' },
      { char: '◎', name: '双圆' },
      { char: '■', name: '实心方块' },
      { char: '□', name: '空心方块' },
      { char: '▲', name: '实心三角形' },
      { char: '△', name: '空心三角形' },
      { char: '▼', name: '实心倒三角' },
      { char: '▽', name: '空心倒三角' },
      { char: '♠', name: '黑桃' },
      { char: '♣', name: '梅花' },
      { char: '♥', name: '红桃' },
      { char: '♦', name: '方块' },
      { char: '♤', name: '白花黑桃' },
      { char: '♧', name: '白花梅花' },
      { char: '♡', name: '白花红桃' },
      { char: '♢', name: '白花方块' },
      { char: '☀', name: '太阳' },
      { char: '☁', name: '云' },
      { char: '☂', name: '雨伞' },
      { char: '☃', name: '雪人' },
      { char: '☄', name: '彗星' },
      { char: '☺', name: '笑脸' },
      { char: '☹', name: '哭脸' },
      { char: '✉', name: '信封' },
      { char: '✂', name: '剪刀' },
      { char: '✎', name: '铅笔' },
      { char: '✒', name: '钢笔' },
      { char: '✓', name: '对号' },
      { char: '✔', name: '粗对号' },
      { char: '✕', name: '错号' },
      { char: '✖', name: '粗错号' },
      { char: '♂', name: '男性' },
      { char: '♀', name: '女性' },
      { char: '♪', name: '八分音符' },
      { char: '♫', name: '十六分音符' },
      { char: '♬', name: '三十二分音符' },
      { char: '♭', name: '降号' },
      { char: '♯', name: '升号' },
      { char: '♔', name: '白心王' },
      { char: '♕', name: '白心后' },
      { char: '♖', name: '白心车' },
      { char: '♗', name: '白心象' },
      { char: '♘', name: '白心马' },
      { char: '♙', name: '白心兵' }
    ]
  },
  {
    name: 'Emoji',
    characters: [
      // 表情 - 基础 Unicode 表情符号，兼容性更好
      { char: '😀', name: '笑脸' },
      { char: '😃', name: '大笑' },
      { char: '😄', name: '开心' },
      { char: '😁', name: '咧嘴笑' },
      { char: '😆', name: '眯眼笑' },
      { char: '😅', name: '汗笑' },
      { char: '😂', name: '笑哭' },
      { char: '🤣', name: '笑到地上打滚' },
      { char: '😊', name: '微笑' },
      { char: '😇', name: '天使' },
      { char: '🙂', name: '浅笑' },
      { char: '🙃', name: '倒脸' },
      { char: '😉', name: '眨眼' },
      { char: '😌', name: '满足' },
      { char: '😍', name: '花痴' },
      { char: '🥰', name: '幸福' },
      { char: '😘', name: '飞吻' },
      { char: '😗', name: '亲吻' },
      { char: '😙', name: '亲亲' },
      { char: '😚', name: '闭眼亲' },
      { char: '😋', name: '好吃' },
      { char: '😛', name: '吐舌' },
      { char: '😜', name: '调皮' },
      { char: '🤪', name: '搞怪' },
      { char: '😝', name: '鬼脸' },
      { char: '🤑', name: '发财' },
      { char: '🤗', name: '拥抱' },
      { char: '🤭', name: '偷笑' },
      { char: '🤫', name: '嘘' },
      { char: '🤔', name: '思考' },
      { char: '🤐', name: '闭嘴' },
      { char: '🤨', name: '怀疑' },
      { char: '😐', name: '无语' },
      { char: '😑', name: '面无表情' },
      { char: '😶', name: '沉默' },
      { char: '😏', name: '坏笑' },
      { char: '😒', name: '不爽' },
      { char: '🙄', name: '白眼' },
      { char: '😬', name: '僵笑' },
      { char: '🤥', name: '说谎' },
      { char: '😔', name: '失落' },
      { char: '😪', name: '困倦' },
      { char: '🤤', name: '流口水' },
      { char: '😴', name: '睡觉' },
      { char: '😷', name: '口罩' },
      { char: '🤒', name: '发烧' },
      { char: '🤕', name: '受伤' },
      { char: '🤢', name: '恶心' },
      { char: '🤮', name: '呕吐' },
      { char: '🤧', name: '打喷嚏' },
      { char: '🥵', name: '热' },
      { char: '🥶', name: '冷' },
      { char: '🥴', name: '迷糊' },
      { char: '😵', name: '眩晕' },
      { char: '🤯', name: '爆炸头' },
      { char: '🤠', name: '牛仔' },
      { char: '🥳', name: '派对' },
      { char: '😎', name: '墨镜' },
      { char: '🤓', name: '书呆子' },
      { char: '🧐', name: '单片眼镜' },
      { char: '😕', name: '困惑' },
      { char: '😟', name: '担心' },
      { char: '🙁', name: '难过' },
      { char: '☹', name: '沮丧' },
      { char: '😮', name: '吃惊' },
      { char: '😯', name: '惊讶' },
      { char: '😲', name: '震惊' },
      { char: '😳', name: '害羞' },
      { char: '🥺', name: '可怜' },
      { char: '😦', name: '失望' },
      { char: '😧', name: '惊恐' },
      { char: '😨', name: '害怕' },
      { char: '😰', name: '冷汗' },
      { char: '😥', name: '尴尬' },
      { char: '😢', name: '哭泣' },
      { char: '😭', name: '大哭' },
      { char: '😱', name: '尖叫' },
      { char: '😖', name: '痛苦' },
      { char: '😣', name: '难受' },
      { char: '😞', name: '沮丧' },
      { char: '😓', name: '汗' },
      { char: '😩', name: '崩溃' },
      { char: '😫', name: '疲惫' },
      { char: '😤', name: '生气' },
      { char: '😡', name: '愤怒' },
      { char: '😠', name: '恼火' },
      { char: '🤬', name: '爆粗' },
      { char: '😈', name: '小恶魔' },
      { char: '👿', name: '恶魔' },
      { char: '💀', name: '骷髅' },
      { char: '☠', name: '骷髅旗' },
      { char: '👻', name: '幽灵' },
      { char: '👽', name: '外星人' },
      { char: '🤖', name: '机器人' },
      { char: '🎃', name: '南瓜' },
      { char: '😺', name: '猫笑' },
      { char: '😸', name: '猫咧嘴' },
      { char: '😹', name: '猫笑哭' },
      { char: '😻', name: '猫花痴' },
      { char: '😼', name: '猫坏笑' },
      { char: '😽', name: '猫亲' },
      { char: '🙀', name: '猫惊讶' },
      { char: '😿', name: '猫哭' },
      { char: '😾', name: '猫生气' },
      { char: '❤', name: '红心' },
      { char: '🧡', name: '橙心' },
      { char: '💛', name: '黄心' },
      { char: '💚', name: '绿心' },
      { char: '💙', name: '蓝心' },
      { char: '💜', name: '紫心' },
      { char: '🖤', name: '黑心' },
      { char: '💔', name: '心碎' },
      { char: '❣', name: '心叹号' },
      { char: '💕', name: '双心' },
      { char: '💞', name: '旋转心' },
      { char: '💓', name: '心跳' },
      { char: '💗', name: '心心' },
      { char: '💖', name: '闪亮心' },
      { char: '💘', name: '丘比特' },
      { char: '💝', name: '礼物心' },
      { char: '💟', name: '心形装饰' },
      // 手势
      { char: '👍', name: '点赞' },
      { char: '👎', name: '差评' },
      { char: '👊', name: '拳头' },
      { char: '✊', name: '握拳' },
      { char: '👏', name: '鼓掌' },
      { char: '🙌', name: '举手庆祝' },
      { char: '🙏', name: '祈祷' },
      { char: '🤝', name: '握手' },
      { char: '💪', name: '力量' },
      { char: '✋', name: '手掌' },
      { char: '🖐', name: '张开手' },
      { char: '🖖', name: '瓦肯手' },
      { char: '🤟', name: '摇滚' },
      { char: '🤘', name: '牛角' },
      { char: '👌', name: 'OK' },
      { char: '✌', name: '胜利' },
      { char: '🤞', name: '交叉手指' },
      { char: '🤙', name: '打电话' },
      { char: '👈', name: '指左' },
      { char: '👉', name: '指右' },
      { char: '👆', name: '指上' },
      { char: '👇', name: '指下' },
      { char: '☝', name: '食指' },
      { char: '✍', name: '写字' },
      { char: '💅', name: '涂指甲' },
      // 自然
      { char: '💐', name: '花束' },
      { char: '🌸', name: '樱花' },
      { char: '🌹', name: '玫瑰' },
      { char: '🌺', name: '芙蓉' },
      { char: '🌻', name: '向日葵' },
      { char: '🌷', name: '郁金香' },
      { char: '🌼', name: '小花' },
      { char: '🌿', name: '树叶' },
      { char: '☘', name: '三叶草' },
      { char: '🍀', name: '幸运草' },
      { char: '🌵', name: '仙人掌' },
      { char: '🌴', name: '棕榈' },
      { char: '🌲', name: '松树' },
      { char: '🌳', name: '大树' },
      { char: '🌈', name: '彩虹' },
      { char: '☀', name: '太阳' },
      { char: '☁', name: '云' },
      { char: '☔', name: '雨伞' },
      { char: '⚡', name: '闪电' },
      { char: '❄', name: '雪花' },
      { char: '🔥', name: '火' },
      { char: '💧', name: '水滴' },
      { char: '🌊', name: '海浪' },
      { char: '🌙', name: '月亮' },
      { char: '⭐', name: '星星' },
      { char: '✨', name: '闪光' },
      // 动物
      { char: '🐶', name: '狗' },
      { char: '🐱', name: '猫' },
      { char: '🐭', name: '老鼠' },
      { char: '🐹', name: '仓鼠' },
      { char: '🐰', name: '兔子' },
      { char: '🦊', name: '狐狸' },
      { char: '🐻', name: '熊' },
      { char: '🐼', name: '熊猫' },
      { char: '🐨', name: '考拉' },
      { char: '🐯', name: '老虎' },
      { char: '🦁', name: '狮子' },
      { char: '🐮', name: '奶牛' },
      { char: '🐷', name: '猪' },
      { char: '🐸', name: '青蛙' },
      { char: '🐵', name: '猴子' },
      { char: '🐔', name: '小鸡' },
      { char: '🐧', name: '企鹅' },
      { char: '🐦', name: '小鸟' },
      { char: '🐤', name: '小鸡' },
      { char: '🐺', name: '狼' },
      { char: '🐗', name: '野猪' },
      { char: '🐴', name: '马' },
      { char: '🐝', name: '蜜蜂' },
      { char: '🦋', name: '蝴蝶' },
      { char: '🐌', name: '蜗牛' },
      { char: '🐞', name: '瓢虫' },
      { char: '🐢', name: '乌龟' },
      { char: '🐍', name: '蛇' },
      { char: '🐙', name: '章鱼' },
      { char: '🦀', name: '螃蟹' },
      { char: '🐠', name: '热带鱼' },
      { char: '🐳', name: '鲸鱼' },
      { char: '🐬', name: '海豚' },
      { char: '🦄', name: '独角兽' },
      // 食物
      { char: '🍎', name: '苹果' },
      { char: '🍐', name: '梨' },
      { char: '🍊', name: '橘子' },
      { char: '🍋', name: '柠檬' },
      { char: '🍌', name: '香蕉' },
      { char: '🍉', name: '西瓜' },
      { char: '🍇', name: '葡萄' },
      { char: '🍓', name: '草莓' },
      { char: '🍒', name: '樱桃' },
      { char: '🍍', name: '菠萝' },
      { char: '🥝', name: '奇异果' },
      { char: '🍅', name: '番茄' },
      { char: '🥑', name: '牛油果' },
      { char: '🥕', name: '胡萝卜' },
      { char: '🌽', name: '玉米' },
      { char: '🥔', name: '土豆' },
      { char: '🍞', name: '面包' },
      { char: '🥚', name: '鸡蛋' },
      { char: '🥓', name: '培根' },
      { char: '🍔', name: '汉堡' },
      { char: '🍟', name: '薯条' },
      { char: '🍕', name: '披萨' },
      { char: '🌭', name: '热狗' },
      { char: '🥪', name: '三明治' },
      { char: '🌮', name: '墨西哥卷' },
      { char: '🌯', name: '卷饼' },
      { char: '🍝', name: '意面' },
      { char: '🍜', name: '拉面' },
      { char: '🍲', name: '火锅' },
      { char: '🍛', name: '咖喱' },
      { char: '🍣', name: '寿司' },
      { char: '🍤', name: '炸虾' },
      { char: '🍰', name: '蛋糕' },
      { char: '🍦', name: '冰淇淋' },
      { char: '🍩', name: '甜甜圈' },
      { char: '🍪', name: '饼干' },
      { char: '🍫', name: '巧克力' },
      { char: '🍿', name: '爆米花' },
      { char: '🍵', name: '茶' },
      { char: '☕', name: '咖啡' },
      { char: '🍺', name: '啤酒' },
      { char: '🍷', name: '红酒' },
      // 活动
      { char: '🎈', name: '气球' },
      { char: '🎉', name: '礼花' },
      { char: '🎊', name: '拉花' },
      { char: '🎁', name: '礼物' },
      { char: '🎀', name: '蝴蝶结' },
      { char: '🎯', name: '靶心' },
      { char: '🎮', name: '游戏机' },
      { char: '🎧', name: '耳机' },
      { char: '🎵', name: '音符' },
      { char: '🎶', name: '音乐' },
      { char: '⚽', name: '足球' },
      { char: '🏀', name: '篮球' },
      { char: '⚾', name: '棒球' },
      { char: '🎾', name: '网球' },
      { char: '🏐', name: '排球' },
      { char: '🏓', name: '乒乓' },
      { char: '🏸', name: '羽毛球' },
      { char: '🏆', name: '奖杯' },
      { char: '🥇', name: '金牌' },
      { char: '🥈', name: '银牌' },
      { char: '🥉', name: '铜牌' },
      { char: '🎤', name: '麦克风' },
      { char: '🎬', name: '场记板' },
      { char: '🎨', name: '调色板' },
      // 交通
      { char: '🚗', name: '汽车' },
      { char: '🚕', name: '出租车' },
      { char: '🚌', name: '公交' },
      { char: '🚓', name: '警车' },
      { char: '🚑', name: '救护车' },
      { char: '🚒', name: '消防车' },
      { char: '🚚', name: '卡车' },
      { char: '🚲', name: '自行车' },
      { char: '✈', name: '飞机' },
      { char: '🚀', name: '火箭' },
      { char: '🚢', name: '轮船' },
      { char: '⛵', name: '帆船' },
      { char: '🚄', name: '高铁' },
      { char: '🚂', name: '火车' },
      { char: '🚇', name: '地铁' },
      // 建筑
      { char: '🏠', name: '房子' },
      { char: '🏢', name: '办公楼' },
      { char: '🏥', name: '医院' },
      { char: '🏫', name: '学校' },
      { char: '🏨', name: '酒店' },
      { char: '🏦', name: '银行' },
      { char: '🏪', name: '便利店' },
      { char: '⛪', name: '教堂' },
      { char: '🏯', name: '城堡' },
      { char: '🗼', name: '铁塔' },
      { char: '🗽', name: '自由女神' },
      // 物品
      { char: '⌚', name: '手表' },
      { char: '📱', name: '手机' },
      { char: '💻', name: '电脑' },
      { char: '⌨', name: '键盘' },
      { char: '📷', name: '相机' },
      { char: '🎥', name: '摄像机' },
      { char: '📺', name: '电视' },
      { char: '📻', name: '收音机' },
      { char: '⏰', name: '闹钟' },
      { char: '📚', name: '书籍' },
      { char: '📖', name: '打开的书' },
      { char: '📝', name: '记笔记' },
      { char: '✏', name: '铅笔' },
      { char: '📌', name: '图钉' },
      { char: '📎', name: '回形针' },
      { char: '🔒', name: '锁' },
      { char: '🔑', name: '钥匙' },
      { char: '🔨', name: '锤子' },
      { char: '💡', name: '灯泡' },
      { char: '🔦', name: '手电筒' },
      { char: '🕯', name: '蜡烛' },
      { char: '💰', name: '钱袋' },
      { char: '💵', name: '钞票' },
      { char: '💳', name: '信用卡' },
      { char: '📦', name: '包裹' },
      { char: '✉', name: '信封' },
      { char: '📩', name: '邮件' },
      // 符号
      { char: '✅', name: '勾选' },
      { char: '❌', name: '叉' },
      { char: '⭕', name: '圆圈' },
      { char: '❗', name: '感叹号' },
      { char: '❓', name: '问号' },
      { char: '‼', name: '双感叹号' },
      { char: '⁉', name: '感叹问号' },
      { char: '⚠', name: '警告' },
      { char: '⛔', name: '禁止' },
      { char: '🚫', name: '禁入' },
      { char: '💯', name: '满分' },
      { char: '💢', name: '愤怒' },
      { char: '💥', name: '爆炸' },
      { char: '💫', name: '眩晕' },
      { char: '💦', name: '汗水' },
      { char: '🎊', name: '彩球' },
      { char: '🎋', name: '七夕树' },
      { char: '🎍', name: '门松' },
      { char: '🚩', name: '旗帜' },
      { char: '🏁', name: '终点旗' }
    ]
  },
  {
    name: '标点符号',
    characters: [
      { char: '、', name: '顿号' },
      { char: '。', name: '句号' },
      { char: '·', name: '间隔号' },
      { char: 'ˉ', name: '间隔符' },
      { char: 'ˇ', name: '抑扬符' },
      { char: '¨', name: '分音符' },
      { char: '〃', name: '同上' },
      { char: '々', name: '叠字符' },
      { char: '「', name: '左直角引号' },
      { char: '」', name: '右直角引号' },
      { char: '『', name: '左双直角引号' },
      { char: '』', name: '右双直角引号' },
      { char: '【', name: '左实心方头括号' },
      { char: '】', name: '右实心方头括号' },
      { char: '〖', name: '左空心方头括号' },
      { char: '〗', name: '右空心方头括号' },
      { char: '〔', name: '左六角括号' },
      { char: '〕', name: '右六角括号' },
      { char: '《', name: '左书名号' },
      { char: '》', name: '右书名号' },
      { char: '〈', name: '左单书名号' },
      { char: '〉', name: '右单书名号' },
      { char: '︵', name: '左圆括号' },
      { char: '︶', name: '右圆括号' },
      { char: '︷', name: '左大括号' },
      { char: '︸', name: '右大括号' },
      { char: '︹', name: '左方括号' },
      { char: '︺', name: '右方括号' },
      { char: '︻', name: '左实心方括号' },
      { char: '︼', name: '右实心方括号' }
    ]
  },
  {
    name: '拼音注音',
    characters: [
      { char: 'ā', name: 'a一声' },
      { char: 'á', name: 'a二声' },
      { char: 'ǎ', name: 'a三声' },
      { char: 'à', name: 'a四声' },
      { char: 'ō', name: 'o一声' },
      { char: 'ó', name: 'o二声' },
      { char: 'ǒ', name: 'o三声' },
      { char: 'ò', name: 'o四声' },
      { char: 'ē', name: 'e一声' },
      { char: 'é', name: 'e二声' },
      { char: 'ě', name: 'e三声' },
      { char: 'è', name: 'e四声' },
      { char: 'ī', name: 'i一声' },
      { char: 'í', name: 'i二声' },
      { char: 'ǐ', name: 'i三声' },
      { char: 'ì', name: 'i四声' },
      { char: 'ū', name: 'u一声' },
      { char: 'ú', name: 'u二声' },
      { char: 'ǔ', name: 'u三声' },
      { char: 'ù', name: 'u四声' },
      { char: 'ü', name: 'v' },
      { char: 'ǖ', name: 'v一声' },
      { char: 'ǘ', name: 'v二声' },
      { char: 'ǚ', name: 'v三声' },
      { char: 'ǜ', name: 'v四声' },
      { char: 'ㄅ', name: 'b' },
      { char: 'ㄆ', name: 'p' },
      { char: 'ㄇ', name: 'm' },
      { char: 'ㄈ', name: 'f' },
      { char: 'ㄉ', name: 'd' },
      { char: 'ㄊ', name: 't' },
      { char: 'ㄋ', name: 'n' },
      { char: 'ㄌ', name: 'l' },
      { char: 'ㄍ', name: 'g' },
      { char: 'ㄎ', name: 'k' },
      { char: 'ㄏ', name: 'h' },
      { char: 'ㄐ', name: 'j' },
      { char: 'ㄑ', name: 'q' },
      { char: 'ㄒ', name: 'x' },
      { char: 'ㄓ', name: 'zh' },
      { char: 'ㄔ', name: 'ch' },
      { char: 'ㄕ', name: 'sh' },
      { char: 'ㄖ', name: 'r' },
      { char: 'ㄗ', name: 'z' },
      { char: 'ㄘ', name: 'c' },
      { char: 'ㄙ', name: 's' },
      { char: 'ㄧ', name: 'i' },
      { char: 'ㄨ', name: 'u' },
      { char: 'ㄩ', name: 'v' },
      { char: 'ㄚ', name: 'a' },
      { char: 'ㄛ', name: 'o' },
      { char: 'ㄜ', name: 'e' },
      { char: 'ㄝ', name: 'ie' },
      { char: 'ㄞ', name: 'ai' },
      { char: 'ㄟ', name: 'ei' },
      { char: 'ㄠ', name: 'ao' },
      { char: 'ㄡ', name: 'ou' },
      { char: 'ㄢ', name: 'an' },
      { char: 'ㄣ', name: 'en' },
      { char: 'ㄤ', name: 'ang' },
      { char: 'ㄥ', name: 'eng' },
      { char: 'ㄦ', name: 'er' }
    ]
  }
]

export const PLUGIN_PREFIX = 'ce-special-characters'
