import { ISpecialCharacterGroup } from '../interface'

export const DEFAULT_CHARACTERS: ISpecialCharacterGroup[] = [
  {
    name: '常用符号',
    characters: [
      { char: '©', name: '版权' },
      { char: '®', name: '注册商标' },
      { char: '™', name: '商标' },
      { char: '§', name: '章节' },
      { char: '¶', name: '段落' },
      { char: '†', name: '剑标' },
      { char: '‡', name: '双剑标' },
      { char: '•', name: '项目符号' },
      { char: '…', name: '省略号' },
      { char: '—', name: '破折号' },
      { char: '–', name: '短破折号' },
      { char: '°', name: '度' },
      { char: '‰', name: '千分号' },
      { char: '‱', name: '万分号' },
      { char: '№', name: '序号' },
      { char: '℗', name: '录音版权' },
      { char: '℠', name: '服务标记' },
      { char: '℡', name: '电话' },
      { char: '℀', name: '账户' },
      { char: '℁', name: '地址' },
      { char: '℅', name: '照顾' },
      { char: '※', name: '米印' },
      { char: '¡', name: '倒感叹号' },
      { char: '¿', name: '倒问号' }
    ]
  },
  {
    name: '数学符号',
    characters: [
      { char: '±', name: '正负' },
      { char: '×', name: '乘' },
      { char: '÷', name: '除' },
      { char: '≠', name: '不等于' },
      { char: '≡', name: '恒等于' },
      { char: '≌', name: '全等于' },
      { char: '≈', name: '约等于' },
      { char: '≃', name: '渐近等于' },
      { char: '≅', name: '同构' },
      { char: '≤', name: '小于等于' },
      { char: '≥', name: '大于等于' },
      { char: '≮', name: '不小于' },
      { char: '≯', name: '不大于' },
      { char: '∞', name: '无穷' },
      { char: '∑', name: '求和' },
      { char: '∏', name: '求积' },
      { char: '√', name: '平方根' },
      { char: '∛', name: '立方根' },
      { char: '∜', name: '四次方根' },
      { char: '∫', name: '积分' },
      { char: '∬', name: '二重积分' },
      { char: '∮', name: '曲线积分' },
      { char: '∂', name: '偏导' },
      { char: '∆', name: '增量' },
      { char: '∇', name: '梯度' },
      { char: 'π', name: '圆周率' },
      { char: '∝', name: '成正比' },
      { char: '∠', name: '角' },
      { char: '∟', name: '直角' },
      { char: '⌒', name: '弧' },
      { char: '∣', name: '整除' },
      { char: '∤', name: '不整除' },
      { char: '∥', name: '平行' },
      { char: '∦', name: '不平行' },
      { char: '⊥', name: '垂直' },
      { char: '∧', name: '逻辑与' },
      { char: '∨', name: '逻辑或' },
      { char: '∩', name: '交集' },
      { char: '∪', name: '并集' },
      { char: '∅', name: '空集' },
      { char: '∈', name: '属于' },
      { char: '∉', name: '不属于' },
      { char: '⊆', name: '包含于' },
      { char: '⊇', name: '包含' },
      { char: '⊂', name: '真包含于' },
      { char: '⊃', name: '真包含' },
      { char: '∵', name: '因为' },
      { char: '∴', name: '所以' },
      { char: '∃', name: '存在' },
      { char: '∀', name: '任意' },
      { char: '¬', name: '非' },
      { char: '⊕', name: '异或' },
      { char: '⊙', name: '同或' }
    ]
  },
  {
    name: '希腊字母',
    characters: [
      { char: 'α', name: 'Alpha' },
      { char: 'β', name: 'Beta' },
      { char: 'γ', name: 'Gamma' },
      { char: 'δ', name: 'Delta' },
      { char: 'ε', name: 'Epsilon' },
      { char: 'ζ', name: 'Zeta' },
      { char: 'η', name: 'Eta' },
      { char: 'θ', name: 'Theta' },
      { char: 'ι', name: 'Iota' },
      { char: 'κ', name: 'Kappa' },
      { char: 'λ', name: 'Lambda' },
      { char: 'μ', name: 'Mu' },
      { char: 'ν', name: 'Nu' },
      { char: 'ξ', name: 'Xi' },
      { char: 'ο', name: 'Omicron' },
      { char: 'π', name: 'Pi' },
      { char: 'ρ', name: 'Rho' },
      { char: 'σ', name: 'Sigma' },
      { char: 'τ', name: 'Tau' },
      { char: 'υ', name: 'Upsilon' },
      { char: 'φ', name: 'Phi' },
      { char: 'χ', name: 'Chi' },
      { char: 'ψ', name: 'Psi' },
      { char: 'ω', name: 'Omega' },
      { char: 'Α', name: 'Alpha大写' },
      { char: 'Β', name: 'Beta大写' },
      { char: 'Γ', name: 'Gamma大写' },
      { char: 'Δ', name: 'Delta大写' },
      { char: 'Ε', name: 'Epsilon大写' },
      { char: 'Ζ', name: 'Zeta大写' },
      { char: 'Η', name: 'Eta大写' },
      { char: 'Θ', name: 'Theta大写' },
      { char: 'Ι', name: 'Iota大写' },
      { char: 'Κ', name: 'Kappa大写' },
      { char: 'Λ', name: 'Lambda大写' },
      { char: 'Μ', name: 'Mu大写' },
      { char: 'Ν', name: 'Nu大写' },
      { char: 'Ξ', name: 'Xi大写' },
      { char: 'Ο', name: 'Omicron大写' },
      { char: 'Π', name: 'Pi大写' },
      { char: 'Ρ', name: 'Rho大写' },
      { char: 'Σ', name: 'Sigma大写' },
      { char: 'Τ', name: 'Tau大写' },
      { char: 'Υ', name: 'Upsilon大写' },
      { char: 'Φ', name: 'Phi大写' },
      { char: 'Χ', name: 'Chi大写' },
      { char: 'Ψ', name: 'Psi大写' },
      { char: 'Ω', name: 'Omega大写' }
    ]
  },
  {
    name: '单位符号',
    characters: [
      // 货币
      { char: '€', name: '欧元' },
      { char: '£', name: '英镑' },
      { char: '¥', name: '日元/人民币' },
      { char: '¢', name: '美分' },
      { char: '＄', name: '美元' },
      { char: '₩', name: '韩元' },
      { char: '₽', name: '卢布' },
      { char: '₹', name: '卢比' },
      // 长度/面积/体积
      { char: '㎜', name: '毫米' },
      { char: '㎝', name: '厘米' },
      { char: 'dm', name: '分米' },
      { char: 'm', name: '米' },
      { char: '㎞', name: '千米' },
      { char: '㎡', name: '平方米' },
      { char: '㎥', name: '立方米' },
      { char: 'μm', name: '微米' },
      { char: 'nm', name: '纳米' },
      { char: 'Å', name: '埃' },
      // 重量
      { char: '㎎', name: '毫克' },
      { char: 'g', name: '克' },
      { char: '㎏', name: '千克' },
      { char: 't', name: '吨' },
      // 容积
      { char: 'mL', name: '毫升' },
      { char: 'L', name: '升' },
      // 温度
      { char: '℃', name: '摄氏度' },
      { char: '℉', name: '华氏度' },
      { char: 'K', name: '开尔文' },
      // 电学/物理
      { char: 'Ω', name: '欧姆' },
      { char: 'μΩ', name: '微欧' },
      { char: 'mΩ', name: '毫欧' },
      { char: 'kΩ', name: '千欧' },
      { char: 'MΩ', name: '兆欧' },
      { char: 'V', name: '伏特' },
      { char: 'A', name: '安培' },
      { char: 'W', name: '瓦特' },
      { char: 'Hz', name: '赫兹' },
      { char: '㎐', name: '赫兹' }
    ]
  },
  {
    name: '数字序号',
    characters: [
      { char: 'Ⅰ', name: '罗马数字1' },
      { char: 'Ⅱ', name: '罗马数字2' },
      { char: 'Ⅲ', name: '罗马数字3' },
      { char: 'Ⅳ', name: '罗马数字4' },
      { char: 'Ⅴ', name: '罗马数字5' },
      { char: 'Ⅵ', name: '罗马数字6' },
      { char: 'Ⅶ', name: '罗马数字7' },
      { char: 'Ⅷ', name: '罗马数字8' },
      { char: 'Ⅸ', name: '罗马数字9' },
      { char: 'Ⅹ', name: '罗马数字10' },
      { char: 'Ⅺ', name: '罗马数字11' },
      { char: 'Ⅻ', name: '罗马数字12' },
      { char: 'ⅰ', name: '小写罗马1' },
      { char: 'ⅱ', name: '小写罗马2' },
      { char: 'ⅲ', name: '小写罗马3' },
      { char: 'ⅳ', name: '小写罗马4' },
      { char: 'ⅴ', name: '小写罗马5' },
      { char: 'ⅵ', name: '小写罗马6' },
      { char: 'ⅶ', name: '小写罗马7' },
      { char: 'ⅷ', name: '小写罗马8' },
      { char: 'ⅸ', name: '小写罗马9' },
      { char: 'ⅹ', name: '小写罗马10' },
      { char: '①', name: '圆圈1' },
      { char: '②', name: '圆圈2' },
      { char: '③', name: '圆圈3' },
      { char: '④', name: '圆圈4' },
      { char: '⑤', name: '圆圈5' },
      { char: '⑥', name: '圆圈6' },
      { char: '⑦', name: '圆圈7' },
      { char: '⑧', name: '圆圈8' },
      { char: '⑨', name: '圆圈9' },
      { char: '⑩', name: '圆圈10' },
      { char: '❶', name: '黑圆圈1' },
      { char: '❷', name: '黑圆圈2' },
      { char: '❸', name: '黑圆圈3' },
      { char: '❹', name: '黑圆圈4' },
      { char: '❺', name: '黑圆圈5' },
      { char: '❻', name: '黑圆圈6' },
      { char: '❼', name: '黑圆圈7' },
      { char: '❽', name: '黑圆圈8' },
      { char: '❾', name: '黑圆圈9' },
      { char: '❿', name: '黑圆圈10' },
      { char: '⑴', name: '括号1' },
      { char: '⑵', name: '括号2' },
      { char: '⑶', name: '括号3' },
      { char: '⑷', name: '括号4' },
      { char: '⑸', name: '括号5' },
      { char: '⑹', name: '括号6' },
      { char: '⑺', name: '括号7' },
      { char: '⑻', name: '括号8' },
      { char: '⑼', name: '括号9' },
      { char: '⑽', name: '括号10' },
      { char: '⒈', name: '点1' },
      { char: '⒉', name: '点2' },
      { char: '⒊', name: '点3' },
      { char: '⒋', name: '点4' },
      { char: '⒌', name: '点5' },
      { char: '⒍', name: '点6' },
      { char: '⒎', name: '点7' },
      { char: '⒏', name: '点8' },
      { char: '⒐', name: '点9' },
      { char: '⒑', name: '点10' },
      { char: '½', name: '二分之一' },
      { char: '⅓', name: '三分之一' },
      { char: '⅔', name: '三分之二' },
      { char: '¼', name: '四分之一' },
      { char: '¾', name: '四分之三' },
      { char: '⅛', name: '八分之一' },
      { char: '⅜', name: '八分之三' },
      { char: '⅝', name: '八分之五' },
      { char: '⅞', name: '八分之七' }
    ]
  },
  {
    name: '箭头符号',
    characters: [
      { char: '←', name: '左箭头' },
      { char: '↑', name: '上箭头' },
      { char: '→', name: '右箭头' },
      { char: '↓', name: '下箭头' },
      { char: '↔', name: '左右箭头' },
      { char: '↕', name: '上下箭头' },
      { char: '⇐', name: '左双箭头' },
      { char: '⇑', name: '上双箭头' },
      { char: '⇒', name: '右双箭头' },
      { char: '⇓', name: '下双箭头' },
      { char: '⇔', name: '左右双箭头' },
      { char: '⇕', name: '上下双箭头' },
      { char: '↖', name: '左上' },
      { char: '↗', name: '右上' },
      { char: '↘', name: '右下' },
      { char: '↙', name: '左下' },
      { char: '↺', name: '逆时针' },
      { char: '↻', name: '顺时针' },
      { char: '↩', name: '返回' },
      { char: '↪', name: '进入' },
      { char: '➔', name: '粗右箭头' },
      { char: '➜', name: '粗右箭头' },
      { char: '➝', name: '三角箭头' },
      { char: '➞', name: '实心箭头' },
      { char: '➟', name: '虚线箭头' },
      { char: '➠', name: '三角虚线' },
      { char: '➡', name: '黑右箭头' },
      { char: '➢', name: '黑三角头' },
      { char: '➤', name: '黑三角头' },
      { char: '➥', name: '黑右下' },
      { char: '➦', name: '黑右上' },
      { char: '➧', name: '黑右' }
    ]
  },
  {
    name: '图形符号',
    characters: [
      { char: '★', name: '实心五角星' },
      { char: '☆', name: '空心五角星' },
      { char: '✦', name: '四角星' },
      { char: '✧', name: '空心四角星' },
      { char: '◆', name: '实心菱形' },
      { char: '◇', name: '空心菱形' },
      { char: '●', name: '实心圆' },
      { char: '○', name: '空心圆' },
      { char: '◎', name: '双圆' },
      { char: '■', name: '实心方块' },
      { char: '□', name: '空心方块' },
      { char: '▲', name: '实心三角形' },
      { char: '△', name: '空心三角形' },
      { char: '▼', name: '实心倒三角' },
      { char: '▽', name: '空心倒三角' },
      { char: '♠', name: '黑桃' },
      { char: '♣', name: '梅花' },
      { char: '♥', name: '红桃' },
      { char: '♦', name: '方块' },
      { char: '♤', name: '白花黑桃' },
      { char: '♧', name: '白花梅花' },
      { char: '♡', name: '白花红桃' },
      { char: '♢', name: '白花方块' },
      { char: '☀', name: '太阳' },
      { char: '☁', name: '云' },
      { char: '☂', name: '雨伞' },
      { char: '☃', name: '雪人' },
      { char: '☄', name: '彗星' },
      { char: '☺', name: '笑脸' },
      { char: '☹', name: '哭脸' },
      { char: '✉', name: '信封' },
      { char: '✂', name: '剪刀' },
      { char: '✎', name: '铅笔' },
      { char: '✒', name: '钢笔' },
      { char: '✓', name: '对号' },
      { char: '✔', name: '粗对号' },
      { char: '✕', name: '错号' },
      { char: '✖', name: '粗错号' },
      { char: '♂', name: '男性' },
      { char: '♀', name: '女性' },
      { char: '♪', name: '八分音符' },
      { char: '♫', name: '十六分音符' },
      { char: '♬', name: '三十二分音符' },
      { char: '♭', name: '降号' },
      { char: '♯', name: '升号' },
      { char: '♔', name: '白心王' },
      { char: '♕', name: '白心后' },
      { char: '♖', name: '白心车' },
      { char: '♗', name: '白心象' },
      { char: '♘', name: '白心马' },
      { char: '♙', name: '白心兵' }
    ]
  },
  {
    name: '标点符号',
    characters: [
      { char: '、', name: '顿号' },
      { char: '。', name: '句号' },
      { char: '·', name: '间隔号' },
      { char: 'ˉ', name: '间隔符' },
      { char: 'ˇ', name: '抑扬符' },
      { char: '¨', name: '分音符' },
      { char: '〃', name: '同上' },
      { char: '々', name: '叠字符' },
      { char: '「', name: '左直角引号' },
      { char: '」', name: '右直角引号' },
      { char: '『', name: '左双直角引号' },
      { char: '』', name: '右双直角引号' },
      { char: '【', name: '左实心方头括号' },
      { char: '】', name: '右实心方头括号' },
      { char: '〖', name: '左空心方头括号' },
      { char: '〗', name: '右空心方头括号' },
      { char: '〔', name: '左六角括号' },
      { char: '〕', name: '右六角括号' },
      { char: '《', name: '左书名号' },
      { char: '》', name: '右书名号' },
      { char: '〈', name: '左单书名号' },
      { char: '〉', name: '右单书名号' },
      { char: '︵', name: '左圆括号' },
      { char: '︶', name: '右圆括号' },
      { char: '︷', name: '左大括号' },
      { char: '︸', name: '右大括号' },
      { char: '︹', name: '左方括号' },
      { char: '︺', name: '右方括号' },
      { char: '︻', name: '左实心方括号' },
      { char: '︼', name: '右实心方括号' }
    ]
  },
  {
    name: '拼音注音',
    characters: [
      { char: 'ā', name: 'a一声' },
      { char: 'á', name: 'a二声' },
      { char: 'ǎ', name: 'a三声' },
      { char: 'à', name: 'a四声' },
      { char: 'ō', name: 'o一声' },
      { char: 'ó', name: 'o二声' },
      { char: 'ǒ', name: 'o三声' },
      { char: 'ò', name: 'o四声' },
      { char: 'ē', name: 'e一声' },
      { char: 'é', name: 'e二声' },
      { char: 'ě', name: 'e三声' },
      { char: 'è', name: 'e四声' },
      { char: 'ī', name: 'i一声' },
      { char: 'í', name: 'i二声' },
      { char: 'ǐ', name: 'i三声' },
      { char: 'ì', name: 'i四声' },
      { char: 'ū', name: 'u一声' },
      { char: 'ú', name: 'u二声' },
      { char: 'ǔ', name: 'u三声' },
      { char: 'ù', name: 'u四声' },
      { char: 'ü', name: 'v' },
      { char: 'ǖ', name: 'v一声' },
      { char: 'ǘ', name: 'v二声' },
      { char: 'ǚ', name: 'v三声' },
      { char: 'ǜ', name: 'v四声' },
      { char: 'ㄅ', name: 'b' },
      { char: 'ㄆ', name: 'p' },
      { char: 'ㄇ', name: 'm' },
      { char: 'ㄈ', name: 'f' },
      { char: 'ㄉ', name: 'd' },
      { char: 'ㄊ', name: 't' },
      { char: 'ㄋ', name: 'n' },
      { char: 'ㄌ', name: 'l' },
      { char: 'ㄍ', name: 'g' },
      { char: 'ㄎ', name: 'k' },
      { char: 'ㄏ', name: 'h' },
      { char: 'ㄐ', name: 'j' },
      { char: 'ㄑ', name: 'q' },
      { char: 'ㄒ', name: 'x' },
      { char: 'ㄓ', name: 'zh' },
      { char: 'ㄔ', name: 'ch' },
      { char: 'ㄕ', name: 'sh' },
      { char: 'ㄖ', name: 'r' },
      { char: 'ㄗ', name: 'z' },
      { char: 'ㄘ', name: 'c' },
      { char: 'ㄙ', name: 's' },
      { char: 'ㄧ', name: 'i' },
      { char: 'ㄨ', name: 'u' },
      { char: 'ㄩ', name: 'v' },
      { char: 'ㄚ', name: 'a' },
      { char: 'ㄛ', name: 'o' },
      { char: 'ㄜ', name: 'e' },
      { char: 'ㄝ', name: 'ie' },
      { char: 'ㄞ', name: 'ai' },
      { char: 'ㄟ', name: 'ei' },
      { char: 'ㄠ', name: 'ao' },
      { char: 'ㄡ', name: 'ou' },
      { char: 'ㄢ', name: 'an' },
      { char: 'ㄣ', name: 'en' },
      { char: 'ㄤ', name: 'ang' },
      { char: 'ㄥ', name: 'eng' },
      { char: 'ㄦ', name: 'er' }
    ]
  }
]

export const PLUGIN_PREFIX = 'ce-special-characters'
